### ISSUE TITLE
Barra notificacions

### ISSUE THREAD

**Issue by francescvm8** [deivids84/MA-XML-12-CATALAN#1]
La barra de notificacions no baixa a miui 12 20.5.7 pero si quan l'idioma esta en castella

**Comment by deivids84** [comment]
Gràcies per l'avís

El dv., 15 de maig 2020, 12:54, Francesc Valenzuela Morera <
notifications@github.com> va escriure:

**Comment by deivids84** [comment]
Hi @ingbrzy notifications crashed with Catalan language. I don’t know what the mistake might be. Do I need to change anything in the translation?
Thanks
